## ?? ??
server:
  port: 9999

## Spring Container ??
spring:
  ## WEB MVC ??
  mvc:
    ## ?? Resource ??
#    static-path-pattern: /resources/**
    ## Servlet ??? ? ???
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  ## ?? ?? ???
  devtools:
    livereload:
      enabled: true #JSP ?? ? ??? reload
    restart:
      enabled: true
  ## ?? ?? ???
  freemarker:
    cache: false  #default ?? true, false ? ?? ? ???? ??? ?? ??? ?? ?? ?
